sudo: required
services:
  - docker

before_install:
  - docker build -t ellis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t ellis/multi-client ./client
  - docker build -t ellis/multi-nginx ./nginx
  - docker build -t ellis/multi-server ./server
  - docker build -t ellis/multi-worker ./worker
 # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push ellis/multi-client
  - docker push ellis/multi-nginx
  - docker push ellis/multi-server
  - docker push ellis/multi-worker
